"""Reliable Playwright download handling for Google Photos."""

from __future__ import annotations

import asyncio
import mimetypes
import re
from pathlib import Path
from urllib.parse import unquote, urlparse

from loguru import logger
from playwright.async_api import APIResponse, Download, Locator, Page, Request, Route

from infrastructure.exceptions import DownloadError


class DownloadManager:
    """Download the currently open Google Photos item without leaving the viewer."""

    def __init__(
        self,
        page: Page | None,
        download_dir: str | Path,
        max_retries: int = 3,
        retry_delay: float = 2.0,
        download_timeout_ms: int = 120_000,
    ) -> None:
        self.page = page
        self.download_dir = Path(download_dir)
        self.max_retries = max_retries
        self.retry_delay = retry_delay
        self.download_timeout_ms = download_timeout_ms
        self.download_dir.mkdir(parents=True, exist_ok=True)

    def _require_page(self) -> Page:
        if self.page is None:
            raise DownloadError("DownloadManager has no active Playwright page.")
        return self.page

    async def download_file(self) -> str:
        """Download the current photo and return its final absolute path."""
        last_error: Exception | None = None

        for attempt in range(1, self.max_retries + 1):
            try:
                downloaded_path = await self._download_once()
                await self._dismiss_open_menu()
                logger.info("File downloaded successfully: {}", downloaded_path)
                return str(downloaded_path)
            except Exception as exc:
                last_error = exc
                logger.warning(
                    "Download failed (attempt {}/{}): {}",
                    attempt,
                    self.max_retries,
                    exc,
                )
                await self._dismiss_open_menu()
                if attempt < self.max_retries:
                    await asyncio.sleep(self.retry_delay)

        raise DownloadError(
            f"Failed to download the current photo after {self.max_retries} attempts."
        ) from last_error

    async def _download_once(self) -> Path:
        """Handle both browser-download and direct-asset-navigation behaviours."""
        page = self._require_page()
        viewer_url = page.url
        download_control = await self._open_download_action()
        loop = asyncio.get_running_loop()
        download_future: asyncio.Future[Download] = loop.create_future()
        asset_url_future: asyncio.Future[str] = loop.create_future()

        def on_download(download: Download) -> None:
            if not download_future.done():
                download_future.set_result(download)

        async def capture_asset_navigation(route: Route, request: Request) -> None:
            if self._is_download_asset_request(request):
                if not asset_url_future.done():
                    asset_url_future.set_result(request.url)
                await route.abort()
                return
            await route.continue_()

        page.on("download", on_download)
        await page.route("**/*", capture_asset_navigation)
        try:
            await self._activate_download_control(download_control)

            done, _ = await asyncio.wait(
                {download_future, asset_url_future},
                timeout=self.download_timeout_ms / 1000,
                return_when=asyncio.FIRST_COMPLETED,
            )
            if not done:
                raise DownloadError(
                    "Google Photos produced neither a browser download nor a signed "
                    "download URL."
                )

            if download_future in done:
                return await self._save_browser_download(download_future.result())

            asset_url = asset_url_future.result()
            logger.debug(
                "Google Photos exposed a signed asset URL instead of a download event: {}",
                asset_url,
            )
            return await self._save_signed_asset(page, asset_url)
        finally:
            page.remove_listener("download", on_download)
            try:
                await page.unroute("**/*", capture_asset_navigation)
            except Exception as exc:
                logger.debug("Unable to remove temporary download route: {}", exc)
            await self._restore_viewer(page, viewer_url)

    @staticmethod
    def _is_download_asset_request(request: Request) -> bool:
        """Recognise the navigation generated by Google Photos' Download action."""
        try:
            parsed = urlparse(request.url)
        except Exception:
            return False

        host = parsed.hostname or ""
        google_asset = host.endswith("googleusercontent.com")
        signed_download_variant = bool(
            re.search(r"(?:=|-)s0-d(?:-|$)", request.url, re.IGNORECASE)
            or "download" in parsed.query.casefold()
        )
        return google_asset and (
            request.is_navigation_request() or signed_download_variant
        )

    async def _save_browser_download(self, download: Download) -> Path:
        failure = await download.failure()
        if failure:
            raise DownloadError(f"Browser reported download failure: {failure}")

        destination = self._unique_destination(download.suggested_filename)
        try:
            await download.save_as(str(destination))
        except Exception as exc:
            raise DownloadError(f"Unable to save download to {destination}") from exc

        self._validate_saved_file(destination)
        return destination.resolve()

    async def _save_signed_asset(self, page: Page, asset_url: str) -> Path:
        response: APIResponse | None = None
        try:
            response = await page.context.request.get(
                asset_url,
                headers={"Referer": page.url},
                timeout=self.download_timeout_ms,
            )
            if not response.ok:
                raise DownloadError(
                    f"Signed Google Photos asset returned HTTP {response.status}."
                )

            body = await response.body()
            if not body:
                raise DownloadError("Signed Google Photos asset response was empty.")

            filename = self._filename_for_response(
                asset_url,
                response.headers,
                page.url,
            )
            destination = self._unique_destination(filename)
            temporary = destination.with_name(f".{destination.name}.part")
            try:
                temporary.write_bytes(body)
                temporary.replace(destination)
            finally:
                if temporary.exists():
                    temporary.unlink(missing_ok=True)

            self._validate_saved_file(destination)
            return destination.resolve()
        except DownloadError:
            raise
        except Exception as exc:
            raise DownloadError(
                "Unable to fetch the signed Google Photos download URL."
            ) from exc
        finally:
            if response is not None:
                try:
                    await response.dispose()
                except Exception:
                    pass

    def _filename_for_response(
        self,
        asset_url: str,
        headers: dict[str, str],
        viewer_url: str,
    ) -> str:
        disposition = headers.get("content-disposition", "")
        encoded = re.search(
            r"filename\*\s*=\s*UTF-8''([^;]+)",
            disposition,
            re.IGNORECASE,
        )
        if encoded:
            candidate = unquote(encoded.group(1).strip().strip('"'))
            if candidate:
                return Path(candidate).name

        plain = re.search(
            r'filename\s*=\s*(?:"([^"]+)"|([^;]+))',
            disposition,
            re.IGNORECASE,
        )
        if plain:
            candidate = (plain.group(1) or plain.group(2) or "").strip()
            if candidate:
                return Path(candidate).name

        photo_match = re.search(r"/photo/([^/?#]+)", viewer_url)
        stem = photo_match.group(1) if photo_match else Path(urlparse(asset_url).path).name
        stem = re.sub(r"[^A-Za-z0-9._-]+", "_", stem or "google-photo-download")

        content_type = headers.get("content-type", "").split(";", 1)[0].strip().casefold()
        extension = {
            "image/jpeg": ".jpg",
            "image/png": ".png",
            "image/webp": ".webp",
            "image/heic": ".heic",
            "image/heif": ".heif",
            "video/mp4": ".mp4",
            "video/quicktime": ".mov",
        }.get(content_type)
        if not extension:
            extension = mimetypes.guess_extension(content_type) or ""
        if extension == ".jpe":
            extension = ".jpg"

        return f"{stem}{extension}"

    async def _activate_download_control(self, control: Locator) -> None:
        """Activate the menu item without waiting for its navigation to complete."""
        handle = await control.element_handle(timeout=5_000)
        if handle is None:
            raise DownloadError("The Google Photos Download action disappeared.")

        try:
            try:
                await control.click(timeout=10_000, no_wait_after=True)
                return
            except Exception as click_error:
                logger.debug(
                    "Normal download click failed; trying the captured DOM element: {}",
                    click_error,
                )

            try:
                await handle.evaluate("element => element.click()")
            except Exception as exc:
                raise DownloadError(
                    "Unable to activate the Google Photos Download action."
                ) from exc
        finally:
            await handle.dispose()

    async def _open_download_action(self) -> Locator:
        """Open the overflow menu and return the actual Download button/menuitem."""
        page = self._require_page()
        await self._show_viewer_controls(page)

        direct_candidates = (
            page.locator("button[aria-label='Download']"),
            page.locator("[role='button'][aria-label='Download']"),
            page.get_by_role("button", name="Download", exact=True),
        )
        direct = await self._first_visible(direct_candidates)
        if direct is not None:
            return direct

        more_candidates = (
            page.locator("button[aria-label='More options']"),
            page.locator("[role='button'][aria-label='More options']"),
            page.get_by_role("button", name="More options", exact=True),
        )
        more_options = await self._first_visible(more_candidates)
        if more_options is None:
            raise DownloadError("Could not find the Google Photos 'More options' control.")

        await more_options.click(timeout=10_000)
        menu = page.locator("[role='menu']:visible").first
        await menu.wait_for(state="visible", timeout=5_000)

        menu_items = page.locator("[role='menuitem'][aria-label^='Download']")
        count = min(await menu_items.count(), 20)
        for index in range(count):
            item = menu_items.nth(index)
            try:
                label = (await item.get_attribute("aria-label") or "").strip()
                text = (await item.inner_text()).strip()
                combined = f"{label} {text}".casefold()
                if "download all" in combined:
                    continue
                if await item.is_visible() and await item.is_enabled():
                    return item
            except Exception:
                continue

        text_matches = page.locator("[role='menuitem']").filter(has_text="Download")
        count = min(await text_matches.count(), 20)
        for index in range(count):
            item = text_matches.nth(index)
            try:
                text = (await item.inner_text()).strip().casefold()
                if text == "download" and await item.is_visible() and await item.is_enabled():
                    return item
            except Exception:
                continue

        await self._dismiss_open_menu()
        raise DownloadError(
            "The Google Photos menu does not contain a usable Download action."
        )

    async def _restore_viewer(self, page: Page, viewer_url: str) -> None:
        """Return to the exact photo if Chromium began the intercepted navigation."""
        if page.is_closed() or page.url == viewer_url:
            return
        logger.warning(
            "Restoring Google Photos viewer after intercepted download navigation: {}",
            viewer_url,
        )
        try:
            await page.goto(
                viewer_url,
                wait_until="domcontentloaded",
                timeout=30_000,
            )
            await page.wait_for_timeout(500)
        except Exception as exc:
            raise DownloadError(
                "The file was handled, but the Google Photos viewer could not be restored."
            ) from exc

    async def _show_viewer_controls(self, page: Page) -> None:
        viewport = page.viewport_size or {"width": 1440, "height": 1000}
        await page.mouse.move(viewport["width"] // 2, viewport["height"] // 2)
        await page.wait_for_timeout(100)
        await page.mouse.move(viewport["width"] // 2, 30)
        await page.wait_for_timeout(300)

    async def _first_visible(self, candidates: tuple[Locator, ...]) -> Locator | None:
        for candidate in candidates:
            count = min(await candidate.count(), 10)
            for index in range(count):
                item = candidate.nth(index)
                try:
                    if await item.is_visible() and await item.is_enabled():
                        return item
                except Exception:
                    continue
        return None

    async def _dismiss_open_menu(self) -> None:
        page = self.page
        if page is None:
            return
        try:
            menu = page.locator("[role='menu']:visible")
            if await menu.count() > 0:
                await page.keyboard.press("Escape")
                await page.wait_for_timeout(100)
        except Exception:
            logger.debug("Unable to dismiss the open Google Photos menu.")

    @staticmethod
    def _validate_saved_file(destination: Path) -> None:
        if not destination.is_file() or destination.stat().st_size <= 0:
            raise DownloadError(f"Downloaded file is missing or empty: {destination}")

    def _unique_destination(self, suggested_filename: str) -> Path:
        """Return a collision-safe path without overwriting an existing photo."""
        safe_name = Path(suggested_filename or "google-photo-download").name
        candidate = self.download_dir / safe_name
        if not candidate.exists():
            return candidate

        stem = candidate.stem
        suffix = candidate.suffix
        counter = 1
        while True:
            alternative = self.download_dir / f"{stem} ({counter}){suffix}"
            if not alternative.exists():
                return alternative
            counter += 1
